bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product, name='delete_product'),
    path('new_product_review/<product_id>',
         views.new_product_review, name='new_product_review'),
]

toki/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('articles/', include('articles.urls')),
    path('bag/', include('bag.urls')),
    path('products/', include('products.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings

from django_countries.fields import CountryField

from products.models import Product
from profiles.models import UserProfile

# the order model which lists the fields used in the checkout order form


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True, related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    original_bag = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=254, null=False, blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added,
        accounting for delivery costs.
        """
        self.order_total = self.lineitems.aggregate(Sum('lineitem_total'))[
            'lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = self.order_total * \
                settings.STANDARD_DELIVERY_PERCENTAGE / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False,
                              on_delete=models.CASCADE, related_name='lineitems')
    product = models.ForeignKey(
        Product, null=False, blank=False, on_delete=models.CASCADE)
    product_size = models.CharField(
        max_length=2, null=True, blank=True)  # XS, S, M, L, XL
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, blank=False, editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models
from profiles.models import User


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'
    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    category = models.ForeignKey(
        'Category', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(
        max_digits=6, decimal_places=2, null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name


class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    review_subject = models.CharField(max_length=60, null=False, blank=False)
    review = models.TextField(null=False, blank=False)
    RATINGS = (
        (0, 'No rating'),
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    rating = models.IntegerField(choices=RATINGS, default=0)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.review_subject

products/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Product, Category
from django.forms import Textarea
from .models import ProductReview

# a product form using the product model to allow for creating/editing a product


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    image = forms.ImageField(
        label='Image', required=False, widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black rounded-50'

# a product review form using the productreview model in order for products to be reviewed


class ProductReviewForm(forms.ModelForm):

    class Meta:
        model = ProductReview
        fields = ['review_subject', 'review', 'rating']
        widgets = {
            'review': Textarea(attrs={'cols': 6, 'rows': 6}),
        }
        labels = {
            'rating': 'Please select a rating'
        }

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower
from .models import Product, Category, ProductReview
from .forms import ProductForm, ProductReviewForm

# Create your views here.


def all_products(request):
    """ A view to show all products, includes sorting and search queries """

    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey

            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))

            if sortkey == 'category':
                sortkey = 'category__name'

            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']

            if not query:
                messages.error(
                    request, "You did not enter anys earch criteria")
                return redirect(reverse('products'))

            queries = Q(name__icontains=query) | Q(
                description__icontains=query)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ A view to show individual product details """

    product = get_object_or_404(Product, pk=product_id)
    product_review_form = ProductReviewForm()
    reviews = ProductReview.objects.filter(
        product_id=product_id).order_by('-date_created')

    context = {
        'product': product,
        'product_review_form': product_review_form,
        'reviews': reviews,
    }

    return render(request, 'products/product_detail.html', context)


@login_required
def add_product(request):
    """Add product to the store"""
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that!')
        return redirect(reverse('home'))
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request, 'Failed to add product. Please ensure the form is valid')
    else:
        form = ProductForm()
    template = 'products/add_product.html'
    context = {
        'form': form
    }
    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """Edit a product in the store"""
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that!')
        return redirect(reverse('home'))
    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(
                request, f'You have succesfully updated {product.name}')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request, f'Failed to edit {product.name}, please ensure the form is valid')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product
    }
    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """Delete a product form the store"""
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that!')
        return redirect(reverse('home'))
    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(
        request, f'Successfully deleted {product.name} from the store!')
    return redirect(reverse('products'))


def new_product_review(request, product_id):
    """
    A view to allow customers to rate
    a product if they are logged in
    """
    product = get_object_or_404(Product, pk=product_id)

    if request.method == 'POST':
        product_review_form = ProductReviewForm(request.POST)
        if product_review_form.is_valid():
            review = product_review_form.save(commit=False)
            review.product = product
            review.user = request.user
            review.save()
            messages.success(
                request, f'Thank you for leaving a review for {product.name}')
            return redirect(reverse('product_detail', args=[product_id]))
    print(product_review_form)
    return redirect(reverse('product_detail', args=[product_id]))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="main">
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
</div>
{% endblock %}

{% block content %}

<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6">
            <hr>
            <h2 class="logo-font mb-4">Product Management</h2>
            <h6 class="text-muted">Add A Product</h6>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-6">
            <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name != 'image' %}
                        {{ field | as_crispy_field }}
                    {% else %}
                        {{ field }}
                    {% endif %}
                {% endfor %}
                <div class="text-right">
                    <a href="{% url 'products' %}" class="btn btn-outline-black rounded-50">Cancel</a>
                    <button class="btn btn-orange rounded-50" type="submit">Add Product</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script>
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="main">
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
</div>
{% endblock %}

{% block content %}

<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-6">
            <hr>
            <h2 class="logo-font mb-4">Product Management</h2>
            <h6 class="text-muted">Edit A Product</h6>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-6">
            <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name != 'image' %}
                        {{ field | as_crispy_field }}
                    {% else %}       
                        {{ field }}
                    {% endif %}
               {% endfor %}
                <div class="text-right">
                    <a href="{% url 'products' %}" class="btn btn-outline-black rounded-50">Cancel</a>
                    <button class="btn btn-orange rounded-50" type="submit">Update Product</button>
                </div>
        </form>
        </div>
    </div>
</div>

{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script>
        $('#new-image').change(function(){
            var file = $('#new-image')[0].files[0];
            ('#filename').text(`IMage will be set to: ${file.name}`)
        })
    </script>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block page_header %}
<div class="main">
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}

<div class="overlay"></div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
            <div class="image-container my-5">
                {% if product.image %}
                <a href="{{ product.image.url }}" target="_blank">
                    <img class="details-image img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                </a>
                {% else %}
                <a href="">
                    <img class="details-image img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                </a>
                {% endif %}
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
            <div class="product-details-container mb-5 mt-md-5">
                <p class="mb-0">{{ product.name }}</p>
                <p class="lead mb-0 text-left font-weight-bold">£{{ product.price }}</p>
                {% if product.category %}
                <p class="small mt-1 mb-0">
                    <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name }}">
                        <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                    </a>
                </p>
                {% endif %}
                {% if product.rating %}
                <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ product.rating }} / 5</small>
                {% else %}
                <small class="text-muted">No Rating</small>
                {% endif %}
                {% if request.user.is_superuser %}
                <small class="ml-3">
                    <a href="{% url 'edit_product' product.id %}">Edit</a>
                    <a href="{% url 'delete_product' product.id %}" class="text-danger">Delete</a>
                </small>
                {% endif %}
                <p class="mt-3">{{ product.description }}</p>
                <form class="form" action="{% url 'add_to_bag' product.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-row">
                        {% with product.has_sizes as s %}
                        {% if s %}
                        <div class="col-12">
                            <p><strong>Size:</strong></p>
                            <select class="form-control rounded-50 w-50" name="product_size" id="id_product_size">
                                <option value="xs">XS</option>
                                <option value="s">S</option>
                                <option value="m" selected>M</option>
                                <option value="l">L</option>
                                <option value="xl">XL</option>
                            </select>
                        </div>
                        {% endif %}
                        <div class="col-12">
                            <p class="mt-3"><strong>Quantity:</strong></p>
                            <div class="form-group w-50">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <button class="decrement-qty btn btn-orange rounded-50"
                                            data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}">
                                            <span class="icon">
                                                <i class="fas fa-minus"></i>
                                            </span>
                                        </button>
                                    </div>
                                    <input class="form-control qty_input" type="number" name="quantity" value="1"
                                        min="1" max="99" data-item_id="{{ product.id }}" id="id_qty_{{ product.id }}">
                                    <div class="input-group-append">
                                        <button class="increment-qty btn btn-orange rounded-50"
                                            data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}">
                                            <span class="icon">
                                                <i class="fas fa-plus"></i>
                                            </span>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col{% if s %}-12 mt-2{% endif %}">
                            <a href="{% url 'products' %}" class="btn btn-outline-black rounded-50 mt-5">
                                <span class="icon">
                                    <i class="fas fa-chevron-left"></i>
                                </span>
                                <span class="text-uppercase">Keep Shopping</span>
                            </a>
                            <input type="submit" class="btn btn-orange rounded-50 text-uppercase mt-5" value="Add to Bag">
                        </div>

                        <input type="hidden" name="redirect_url" value="{{ request.path }}">
                        {% endwith %}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="container container-fluid">
    <div class="row mt-5">
        <div class="col col-lg-8 offset-lg-2">
            <h4 class="text-uppercase">Product Reviews <i class="fas fa-angle-down"></i></h4>
            <hr>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-12 col-sm-6 col-md-6 col-lg-4 offset-lg-2 mb-4">
            {% if reviews %}
            {% for review in reviews %}
            <div class="mb-3">
                <div class="logo-font">
                    <span class="mr-3 text-muted"><i class="fas fa-user"></i> {{ review.user.username }}</span>
                    <span class="mr-3 text-muted"><i class="fas fa-user"></i> {{ review.review_subject }}</span>
                    <span class="text-muted"><i class="fas fa-clock"></i> {{ review.date_created }}</span>
                    <div class="review-rating float-right">
                        <i class="fas fa-star{% if review.rate < 1 %}-o empty{% endif %}"></i>
                        <i class="fas fa-star{% if review.rate < 2 %}-o empty{% endif %}"></i>
                        <i class="fas fa-star{% if review.rate < 3 %}-o empty{% endif %}"></i>
                        <i class="fas fa-star{% if review.rate < 4 %}-o empty{% endif %}"></i>
                        <i class="fas fa-star{% if review.rate < 5 %}-o empty{% endif %}"></i>
                    </div>
                    <div class="mt-2">
                        <p><strong>{{ review.subject }}</strong></p>
                    </div>
                </div>
                <div class="review-body">
                    {{ review.review }}
                </div>
            </div>
            <hr>
            {% endfor %}
            {% else %}
            <p>This product has no reviews yet</p>
            {% endif %}
        </div>
        <div class="col-12 col-sm-6 col-md-6 col-lg-4 form-bg p-3">
            <h5 class="text-uppercase">Write a review</h5>
            <form action="{% url 'new_product_review' product.id %}" method="POST" class="form-group review-form">
                {% csrf_token %}
                {{ product_review_form | crispy }}
                {% if user.is_authenticated %}
                <button class="btn btn-outline-black rounded-50 mt-5">
                    <span class="text-uppercase">Add review</span>
                </button>
                {% else %}
                <p>Only registered accounts are permitted to leave reviews<a
                        href="{% url 'account_login' %}"><br>Login</a>
                    or <a href="{% url 'account_signup' %}">Register</a></p>
                {% endif %}
            </form>
        </div>
    </div>
</div>

{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}